# Generated by Django 6.0.1 on 2026-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('research', 'Research'), ('healthTech', 'Health Tech'), ('education', 'Education'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('science', 'Science'), ('finance', 'Finance'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('cultural', 'Cultural'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('announcement', 'Announcement'), ('achievement', 'Achievement'), ('academic', 'Academic'), ('research', 'Research'), ('partnership', 'Partnership'), ('innovation', 'Innovation'), ('sports', 'Sports'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
