# Generated by Django 6.0.1 on 2026-04-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_category_events_category_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('journal', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
